### ISSUE TITLE
Make Navbar highlight the page at which User is at

### ISSUE THREAD

**Issue by Rha02** [shohinsan/skinny-movers#4]
Right now, regardless of what page the user is in, the navbar is highlighting the "Home" button.
The navbar should be updated to that other buttons are highlighted in their respective pages.

**Comment by shohinsan** [comment]
Resolved

**Comment by Rha02** [comment]
The "About" page is a drop down menu, so when I click it, it doesn't change the page, but the navbar continues to highlight it. Navbar should only highlight it when we are in one of the pages inside the dropdown menu.

**Comment by Rha02** [comment]
Navbar does not highlight current page when viewed in mobile (small) screens.
